name: Report GitHub Contribution Stats

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Query GitHub GraphQL and generate report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Saikumar3035
        run: |
          python - <<'PY'
          import os, sys, requests, datetime, subprocess

          TOKEN = os.getenv("GITHUB_TOKEN")
          USERNAME = os.getenv("USERNAME")
          if not TOKEN or not USERNAME:
              print("GITHUB_TOKEN and USERNAME must be set")
              sys.exit(1)

          to_dt = datetime.datetime.utcnow()
          from_dt = to_dt - datetime.timedelta(days=365)
          from_iso = from_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
          to_iso = to_dt.strftime("%Y-%m-%dT%H:%M:%SZ")

          query = """
          query($login:String!, $from:DateTime!, $to:DateTime!) {
            user(login: $login) {
              contributionsCollection(from: $from, to: $to) {
                totalCommitContributions
                contributionCalendar {
                  weeks {
                    contributionDays {
                      date
                      contributionCount
                    }
                  }
                }
              }
            }
          }
          """

          variables = {"login": USERNAME, "from": from_iso, "to": to_iso}
          headers = {"Authorization": f"bearer {TOKEN}"}
          resp = requests.post("https://api.github.com/graphql", json={"query": query, "variables": variables}, headers=headers)
          resp.raise_for_status()
          data = resp.json()

          if "errors" in data:
              print("GraphQL returned errors:", data["errors"])
              sys.exit(1)

          coll = data["data"]["user"]["contributionsCollection"]
          total_commits = coll.get("totalCommitContributions", 0)
          weeks = coll.get("contributionCalendar", {}).get("weeks", [])

          weekly_has = [any(day.get("contributionCount", 0) > 0 for day in w.get("contributionDays", [])) for w in weeks]

          longest = cur = 0
          for v in weekly_has:
              if v:
                  cur += 1
                  if cur > longest: longest = cur
              else:
                  cur = 0

          current_week_contributed = weekly_has[-1] if weekly_has else False

          now_iso = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
          md = f"""# GitHub Contribution Stats for {USERNAME}

- Report generated: {now_iso}
- Window checked: {from_iso} → {to_iso} (last 365 days)
- **Total commit contributions (in window):** {total_commits}
- **Longest GitWeek streak (consecutive calendar weeks with ≥1 contribution):** {longest}
- **Contributed this current week?** {"Yes" if current_week_contributed else "No"}

> Note: This uses `contributionsCollection.totalCommitContributions` from GitHub GraphQL.
> It includes contributions counted by GitHub for the specified 365-day window.
"""

          path = "GITHUB_STATS.md"
          with open(path, "w", encoding="utf-8") as f:
              f.write(md)

          subprocess.run(["git", "add", path], check=False)
          res = subprocess.run(["git", "diff", "--staged", "--quiet"], check=False)
          if res.returncode != 0:
              subprocess.run(["git", "config", "user.name", "github-actions[bot]"], check=True)
              subprocess.run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"], check=True)
              subprocess.run(["git", "commit", "-m", f"Update GitHub stats for {USERNAME} ({now_iso})"], check=True)
              subprocess.run(["git", "push"], check=True)
          else:
              print("No changes to commit.")
          PY

      - name: Show generated file
        run: |
          echo "=== GITHUB_STATS.md ==="
          cat GITHUB_STATS.md || true
